Fixed issue with substitutes and unicode.
Previously I would get the following error, since only the values were in unicode.

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./MarkdownTOC.py", line 292, in run
  File "./MarkdownTOC.py", line 100, in find_tag_and_insert
  File "./MarkdownTOC.py", line 187, in get_toc
  File "./MarkdownTOC.py", line 232, in replace_chars_in_id
TypeError: character mapping must return integer, None or unicode
```